---
title: "README"
format: md
author: aa-kylukov@yandex.ru
---

# Исследование вредоносной активности в домене Windows

## Цель работы
1. Закрепить навыки исследования данных журнала Windows Active Directory
2. Изучить структуру журнала системы Windows Active Directory
3. Зекрепить практические навыки использования языка программирования R для обработки данных
4. Закрепить знания основных функций обработки данных экосистемы tidyverse языка R

## Исходные данные
1. Ноутбук с ОС MacOS
2. RStudio
3. Интерпретатор языка R 4.5.1
4. Доступ в интернет

## Общий план выполнения
1. Импорт данных
2. Нормализация данных
3. Анализ данных

### Шаг 0. Загрузка библиотек
```{R}
library(jsonlite)
library(dplyr)
library(tidyr)
library(purrr)
library(tidyverse)
```

### Шаг 1. Импорт данных
```{R}
dataset_url <- "https://storage.yandexcloud.net/iamcth-data/dataset.tar.gz"
local_archive_name <- "dataset.tar.gz"
if (!file.exists(local_archive_name)) {
  download.file(url = dataset_url, destfile = local_archive_name, mode = "wb")
}
archive_contents <- untar(tarfile = local_archive_name, list = TRUE)
json_file_name <- archive_contents[grep("\\.json$", archive_contents)]
temp_json_dir <- tempdir()
untar(tarfile = local_archive_name, files = json_file_name, exdir = temp_json_dir)
json_file_path <- file.path(temp_json_dir, json_file_name)
json_file_conn <- file(json_file_path, open = "r")
logs <- stream_in(json_file_conn)
```

### Шаг 2. Нормализация данных
```{R}
logs_clean <- logs %>%
  unnest(cols = c(event, winlog, host, agent), names_sep = "_")

logs_clean <- logs_clean %>%
  select(where(~n_distinct(.) > 1))

glimpse(logs_clean)
```

### Шаг 3. Нахождение уникальных хостов в датафрейме
```{R}
logs_clean %>%
  distinct(winlog_computer_name) %>%
  count()
```

### Шаг 4. Подготовка справочника Event_ID
```{R}
library(xml2)
library(rvest)
library(dplyr)

webpage_url <- "https://learn.microsoft.com/en-us/windows-server/identity/ad-ds/plan/appendix-l--events-to-monitor"
webpage <- read_html(webpage_url)
event_df <- html_table(webpage, fill = TRUE)[[1]]
names(event_df)

event_df <- event_df %>%
  rename(
    Event_ID    = `Current Windows Event ID`,
    Legacy_ID   = `Legacy Windows Event ID`,
    Criticality = `Potential Criticality`,
    Summary     = `Event Summary`
  ) %>%
  mutate(Event_ID = suppressWarnings(as.integer(Event_ID))) %>%
  filter(!is.na(Event_ID))

glimpse(event_df)

```

### Шаг 5. Нахождение событий с высоким и средним уровнем критичности
```{R}
logs_with_events <- logs_clean %>%
  left_join(event_df, by = c("winlog_event_id" = "Event_ID"))

logs_with_events <- logs_with_events %>%
  mutate(
    Severity = case_when(
      grepl("High", Criticality, ignore.case = TRUE)   ~ "High",
      grepl("Medium", Criticality, ignore.case = TRUE) ~ "Medium",
      TRUE                                             ~ "Other"
    )
  )

severity_count <- logs_with_events %>%
  filter(Severity %in% c("High", "Medium")) %>%
  count(Severity)

severity_levels <- tibble(
  Severity = c("High", "Medium"),
  n = c(0, 0)
)

severity_final <- severity_levels %>%
  left_join(severity_count, by = "Severity") %>%
  mutate(n = coalesce(n.y, n.x)) %>%
  select(Severity, n)

print(severity_final)

```

## Оценка результата 
В ходе работы была проанализирована выгрузка из SIEM‑системы организации на предмет возможной компрометации.

##Вывод 
Исследование позволило изучить структуру журнала Windows Active Directory, закрепить навыки обработки данных в R и освоить основные функции экосистемы tidyverse.